#just for tac
statistics=true
job=Job_Cargue_Log_Proceso_Incremento
jobVersion=0.1
date=2022-03-19 003922604
contextName=Default
jobId=_FB5cgDC1EeungYVfVw21_w
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=IMT
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=